version: "3.7"

services:
  client:
    extends:
      file: ./client/docker-compose.yml
      service: web
    links:
      - server
    networks:
      - app_net
  server:
    extends:
      file: ./server/docker-compose.yml
      service: api
    networks:
      - app_net

networks:
  app_net:
    driver: bridge