version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/api
      - /api/node_modules
    command: npm run dev
    ports:
      - "4040:4040"
      - "9229:9229"
    env_file:
      - .env
    restart: always

  

networks:
  backend:
    driver: bridge